apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: impala-coordinator-{{ .Values.name }}
spec:
  serviceName: impala-coordinator-{{ .Values.name }}
  replicas: 1
  selector:
    matchLabels:
      name: impala-coordinator-{{ .Values.name }}
  template:
    metadata:
      labels:
        name: impala-coordinator-{{ .Values.name }}
    spec:
      containers:
        - name: impala-coordinator-{{ .Values.name }}
          image: {{ .Values.registry }}/impala-server:{{ .Values.tag }}
          imagePullPolicy: Always
          command: ['bash', '-c', '/opt/hadoop/run-coordinator.sh']
          resources:
            requests:
              memory: "4096Mi"
              cpu: "2000m"
            limits:
              memory: "4096Mi"
              cpu: "2000m"
          ports:
            - containerPort: 21000
              name: im-sr
              protocol: TCP
            - containerPort: 22000
              name: im-sr2x
              protocol: TCP
            - containerPort: 23000
              name: im-sr3
              protocol: TCP
            - containerPort: 25000
              name: im-sr-web
              protocol: TCP
          env:
            - name: IMPALA_STATESTORE
              value: impala-statestore-{{ .Values.name }}
            - name: IMPALA_CATALOG
              value: impala-catalog-{{ .Values.name }}
          volumeMounts:
            - name: config-volume
              mountPath: /etc/alternatives/impala-conf/hdfs-site.xml
              subPath: hdfs-site.xml
            - name: config-volume
              mountPath: /etc/alternatives/impala-conf/core-site.xml
              subPath: core-site.xml
      volumes:
        - name: config-volume
          configMap:
            name: impala-config
